---
layout: post
title: "Part1: Data pre-processing in R"
date: 2018-12-01
categories: datascience
tags: pre-processing importing
---

Background
----------

This is part 1 of a series that I will be posting on the application of
Data Science techniques to process and build predictive machine learning
for environmental data. The data I chose is a publicly available US
lakes water quality data found on U.S. Environmental Protection Agency
(USEPA)
(<a href="https://www.epa.gov/national-aquatic-resource-surveys/nla" class="uri">https://www.epa.gov/national-aquatic-resource-surveys/nla</a>).
The water quality data is for over 1000 lakes found in the US for a
survey done in the year 2007 and 2012. The resulting data comprises
biological, chemical and human land use features.

Research questions
------------------

In general, I want to demonstrate the power of Data science tools and
techniques to process, visualize and do an indepth analysis of data to
again insights and understand of the system. Specifically, the main
questions I would like to answer in this project include the following:

-   Can we reliably predict chlorophyll-a concentration in lakes?
-   What are the important features need for chlorophyll-a prediction?
-   What are the different clusters of US lakes?
    -   Is there any significant difference between urban and rular, and
        manmande and natural lakes?

In this post I will be focusing on data preprocessing task. The next
series will cover missing data imputation, exploratory data analysis,
feature selection, regression and classification.

Load the data
-------------

EPA provides the data for the lakes water quality on there website for
free at \[wwww.epa.com\]. I have downloaded the csv files from this
website and stored it in my local hard disk. In this section I will
import several of these dataset that will be used for the analysis in
this project.

### Load 2007 data

First, I will load the data for 2007 dataset. Since the different water
quality features are given in a separate csv files, I will read them one
by one and merge them later into one dataframe. The details of each
features can be found in the above website link given.

``` r
library(dplyr)
library(reshape2)

# Read landused metrics
lakes_lu07 <- read.csv("data/Lakes/final/nla2007_basin_landuse_metrics.csv", header = T, stringsAsFactors = F)
dim(lakes_lu07)
```

    ## [1] 1157   59

``` r
# Read lakes dissolved oxygen data
lakes_do07 <- read.csv("data/Lakes/final/nla2007_meando_cond.csv", header = T, stringsAsFactors = F)
dim(lakes_do07)
```

    ## [1] 1252   17

``` r
# Read lakes Physical habitat condition data
lakes_phy07 <- read.csv("data/Lakes/final/nla2007_phab_indexvalues.csv", header = T, stringsAsFactors = F)
dim(lakes_phy07)
```

    ## [1] 1442   45

``` r
# Read sampled lakes information
lakes_info07 <- read.csv("data/Lakes/final/nla2007_sampledlakeinfo.csv", header = T, stringsAsFactors = F)
dim(lakes_info07)
```

    ## [1] 1252   47

``` r
# Read lakes secchi depth data
lakes_secchi07 <- read.csv("data/Lakes/final/nla2007_secchi.csv", header = T, stringsAsFactors = F)
dim(lakes_secchi07)
```

    ## [1] 1252    3

``` r
# Read lakes trophic level estimate data
lakes_troph07 <- read.csv("data/Lakes/final/nla2007_trophic_conditionestimate.csv", header = T, stringsAsFactors = F)
dim(lakes_troph07)
```

    ## [1] 1252   12

``` r
# Read lakes trophic level estimate data
lakes_chem07 <- read.csv("data/Lakes/final/EPA_NLA_CHEM07.csv", header = T, stringsAsFactors = F)
dim(lakes_chem07)
```

    ## [1] 1326   28

Next, let us join the data frames into one data frame using `left_join`
function from `dplyr` package by their <em>site id </em>.

``` r
lakes.07 <- full_join(lakes_chem07, lakes_do07) %>% full_join(lakes_info07) %>%
  full_join(lakes_phy07) %>% full_join(lakes_secchi07) %>% full_join(lakes_troph07)

dim(lakes.07)
```

    ## [1] 3652  120

``` r
length(unique(lakes.07$SITE_ID))
```

    ## [1] 1157

``` r
#write.csv(lakes.07, "lakes.07.csv")
names(lakes.07)
```

    ##   [1] "SITE_ID"         "DATE_COL"        "DATECHEM"       
    ##   [4] "PH_FIELD"        "PH_LAB"          "COND"           
    ##   [7] "ANC"             "TURB"            "TOC"            
    ##  [10] "DOC"             "NH4N_PPM"        "NO3_NO2"        
    ##  [13] "NTL_PPM"         "PTL"             "CL_PPM"         
    ##  [16] "NO3N_PPM"        "SO4_PPM"         "CA_PPM"         
    ##  [19] "MG_PPM"          "NA_PPM"          "K_PPM"          
    ##  [22] "COLOR"           "SIO2"            "NH4ION"         
    ##  [25] "CATSUM"          "ANSUM2"          "CHLA"           
    ##  [28] "SECMEAN"         "VISIT_NO"        "LAT_DD"         
    ##  [31] "LON_DD"          "ST"              "EPA_REG"        
    ##  [34] "URBAN"           "NUT_REG"         "NUTREG_NAME"    
    ##  [37] "ECO_NUTA"        "LAKE_ORIGIN"     "ECO3_X_ORIGIN"  
    ##  [40] "REF_CLUSTER"     "RT_NLA"          "HUC_2"          
    ##  [43] "HUC_8"           "DO2_2M"          "SAMPLED"        
    ##  [46] "REPEAT"          "ALBERS_X"        "ALBERS_Y"       
    ##  [49] "FLD_LON_DD"      "FLD_LAT_DD"      "STATE_NAME"     
    ##  [52] "CNTYNAME"        "NHDNAME"         "LAKENAME"       
    ##  [55] "MDCATY"          "WGT"             "WGT_NLA"        
    ##  [58] "ADJWGT_CAT"      "WSA_ECO3"        "WSA_ECO9"       
    ##  [61] "ECO_LEV_3"       "ECO_L3_NAM"      "REFCLUS_NAME"   
    ##  [64] "REF_NUTR"        "AREA_HA"         "SIZE_CLASS"     
    ##  [67] "LAKEAREA"        "LAKEPERIM"       "SLD"            
    ##  [70] "DEPTH_X"         "DEPTHMAX"        "ELEV_PT"        
    ##  [73] "COM_ID"          "REACHCODE"       "DATEPHAB"       
    ##  [76] "CLASSP"          "EcoP6"           "ssiBedBld"      
    ##  [79] "ssiNATBedBld"    "rviLowWood"      "RVegQ_7"        
    ##  [82] "RVegQ_8"         "L_RVegQ_8"       "LRCVQ_7A"       
    ##  [85] "LRCVQ_7B"        "LRCVQ_7C"        "LRCVQ_7D"       
    ##  [88] "LRCVQ_8D"        "L_LRCVQ_8D"      "ElevXLat"       
    ##  [91] "ElevDLat"        "ElevXLon"        "XER"            
    ##  [94] "XER_X_Elev"      "WMT"             "RDisIXAgAdj5"   
    ##  [97] "RDisIXAgAdj4"    "RDisIXAgAdj3"    "RDisIXAgAdj2"   
    ## [100] "RDis_InEx"       "RDis_IX"         "RvegQ_Var"      
    ## [103] "RVegQ"           "LogRVegQ"        "LitCvrQ_Var"    
    ## [106] "LitCvrQ"         "LogLitCvrQ"      "LitRipCVQ_Var"  
    ## [109] "LitRipCVQ"       "LogLitRipCvQ"    "RVeg_OE"        
    ## [112] "LitCvr_OE"       "LitRipCvr_OE"    "DATE_SECCHI"    
    ## [115] "NTL"             "CLEAR_TO_BOTTOM" "TSTATE_TP"      
    ## [118] "TSTATE_TN"       "TSTATE_CHL"      "TSTATE_SECCHI"

This data has 3652 obseravations and 120 features, but only 1157 unique
site ids. This implies, some of the lakes have one sampling while some
have more tha sampling done in the year 2007. Thus, to be consistent and
simplify the analysis we can take the average for those lakes with
sampling effort more than one.

``` r
# Aggregate only the numeric features by site id
lakes.07.agg <- lakes.07 %>% group_by(SITE_ID) %>% summarise_if(is.numeric, mean, na.rm=T) %>% ungroup()

# Aggregate the character features
lakes.07.char <- lakes.07 %>% group_by(SITE_ID) %>% summarise_if(is.character, max)

# Check if the two dataframes match
length(intersect(lakes.07.agg$SITE_ID, lakes.07.char$SITE_ID))
```

    ## [1] 1157

``` r
# combine the two data frames
lakes.07.df <- data.frame(left_join(lakes.07.agg, lakes.07.char))
```

    ## Joining, by = "SITE_ID"

``` r
dim(lakes.07.df)
```

    ## [1] 1157  120

``` r
length(unique(lakes.07.df$SITE_ID))
```

    ## [1] 1157

### Load 2012 data

In this section I will load the data for 2012 and similar to the 2007,
then I will aggregate the different data into one dataframe.

``` r
library(dplyr)
# Read lakes water chemistry data
lakes_chem12 <- read.csv("data/Lakes/final/nla2012_waterchem_wide.csv", 
                         header = T, stringsAsFactors = F)
dim(lakes_chem12)
```

    ## [1] 1230   21

``` r
# Read lakes water chemistry profile data
lakes_prof12 <- read.csv("data/Lakes/final/nla2012_wide_profile.csv", 
                         header = T, stringsAsFactors = F)
dim(lakes_prof12)
```

    ## [1] 30717    56

``` r
# Aggregate profile data using the average

lakes_prof_agg <- aggregate(cbind(OXYGEN, PH, TEMPERATURE, DEPTH, CONDUCTIVITY) ~ UID, FUN = mean, data=lakes_prof12)
lakes_prof_agg2 <- aggregate(cbind(INDEX_LAT_DD, INDEX_LON_DD) ~ UID, FUN = mean, data=lakes_prof12)


# Lakes site information
lakes_info12 <- read.csv("data/Lakes/final/nla2012_wide_siteinfo.csv", 
                         header = T, stringsAsFactors = F)

# Read lakes secchi depth
lakes_secch12 <- read.csv("data/Lakes/final/nla2012_secchi.csv", 
                         header = T, stringsAsFactors = F)
dim(lakes_secch12)
```

    ## [1] 1221   13

``` r
# Read lakes chlorophyl data
lakes_chla12 <- read.csv("data/Lakes/final/nla2012_chla_wide.csv", 
                         header = T, stringsAsFactors = F)
dim(lakes_chla12)
```

    ## [1] 1230    7

``` r
# Read key variables data
lakes_key12 <- read.csv("data/Lakes/final/nla12_keyvariables_data.csv", 
                         header = T, stringsAsFactors = F)
dim(lakes_key12)
```

    ## [1] 1138   50

``` r
lakes_key12small <- select(lakes_key12, UID,SITE_ID, MMI_BENT_NLA12, MMI_ZOOP_NLA6, AMITOTAL, LitCvrQc3OE, LitRipCvrQc3OE, RDis_IX, RVegQc3OE, MICX_RESULT, ATRAZINE_RESULT, TOTALHG_RESULT, METHYLMERCURY_RESULT)

# Read lakes condition data
lakes_cond12 <- read.csv("data/Lakes/final/nla_2012_condition_categories.csv", 
                         header = T, stringsAsFactors = F)
dim(lakes_cond12)
```

    ## [1] 1038   51

``` r
# Read lakes condition data
lakes_phyto12 <- read.csv("data/Lakes/final/nla2012_wide_phytoplankton_count.csv", 
                         header = T, stringsAsFactors = F)
dim(lakes_phyto12)
```

    ## [1] 38627    29

``` r
# Read lakes physical habitat condition data
lakes_phab12 <- read.csv("data/Lakes/final/nla2012_wide_phab.csv", 
                         header = T, stringsAsFactors = F)
dim(lakes_phab12)
```

    ## [1] 33187   115

``` r
lakes_basinarea <- select(lakes_lu07, SITE_ID, BASINAREA_HA)
names(lakes_basinarea)[1] <- "SITEID_07"

# Merge all the data frames into one


lakes_data <- left_join(lakes_chem12,lakes_chla12, by="UID")
lakes_data <- left_join(lakes_data, lakes_cond12, by="UID")
lakes_data <- left_join(lakes_data, lakes_info12, by="UID")
lakes_data <- left_join(lakes_data, lakes_prof_agg, by="UID")
lakes_data <- left_join(lakes_data, lakes_prof_agg2, by="UID")
lakes_data <- left_join(lakes_data, lakes_secch12, by="UID")
lakes_data <- left_join(lakes_data, lakes_key12, by="UID")
#lakes_data <- left_join(lakes_data, lakes_basinarea, by="SITEID_07")

lakes_phyto <- aggregate(ABUNDANCE ~ UID, FUN = sum, data=lakes_phyto12)
lakes_data <- left_join(lakes_data, lakes_phyto)
```

    ## Joining, by = "UID"

``` r
# Remove reapted columns
lakes_data <- select(lakes_data, -ends_with(".y"))
dim(lakes_data)
```

    ## [1] 1230  170

``` r
#Clean column names
names(lakes_data) <- gsub(".x|_RESULT", "", names(lakes_data))

# Select key features
select_lakes <- subset(lakes_data, select=c(UID:TURB, CHLX, CHLL, OXYGEN, PH, TEMPERATURE, DEPTH, CONDUCTIVITY,SECCHI, AREA_HA, ELEVATION,ABUNDANCE,PERIM_KM, INDEX_LAT_DD, INDEX_LON_DD, MMI_BENT_NLA12, MMI_ZOOP_NLA6, AMITOTAL, LitCvrQc3OE, LitRipCvrQc3OE, RDis_IX, RVegQc3OE, MICX, ATRAZINE, METHYLMERCURY, TOTALHG,  URBAN, LAKE_ORIGIN))

select_lakes$URBAN <- as.factor(select_lakes$URBAN)
select_lakes$LAKE_ORIGIN <- as.factor(select_lakes$LAKE_ORIGIN)

dim(select_lakes)
```

    ## [1] 1230   48

Summaries of the data
---------------------

First, I will define a custom function to calculate basic summaries of
the features and returns in a data frame format. Then this function will
be used to do summary statistics on the data. Alternatively, we could
use the `summary` function in base R, however, this will not produce a
pretty output. Note that, the function below handles only numeric data.
But it is possible to extend the function to handle categorical data
also.

``` r
# Summary function
# Calculate summary statistics

summaries <- function(x){
  x_summary <- matrix(0, ncol(x),5)
  for (i in 1:ncol(x)) {
    x_summary[i,] <- c(min(x[,i], na.rm=T), 
                       max(x[,i], na.rm = T), 
                       sd(x[,i], na.rm = T), 
                       mean(x[,i], na.rm=T), 
                       sum(is.na(x[,i])) )
   }

  x_summary <- data.frame(round(x_summary,3), row.names = names(x))
  names(x_summary) <- c("min", "max", "sd", "mean", "NAs")
  return(x_summary)
  
}
```

### Summary of 2012 data

We can use the above defined function to do summary statistics on the
aggregated data for the year 2012.

``` r
library(kableExtra)
# Let's drop TSS which has mostly missing data and reapted var PH.1
select_lakes <- select(select_lakes, -TSS, -PH.1)

lakes_summ <- summaries(select_lakes[,2:44])

lakes_summ %>% kable(format='markdown', digits = 3)%>% kable_styling(bootstrap_options = "striped", full_width = F, font_size = 12)
```

    ## Warning in kable_styling(., bootstrap_options = "striped", full_width =
    ## F, : Please specify format in kable. kableExtra can customize either HTML
    ## or LaTeX outputs. See https://haozhu233.github.io/kableExtra/ for details.

|                  |        min|         max|         sd|      mean|  NAs|
|:-----------------|----------:|-----------:|----------:|---------:|----:|
| ALUMINUM         |      0.000|       3.793|      0.145|     0.023|  168|
| AMMONIA\_N       |      0.000|       3.180|      0.132|     0.037|    1|
| ANC              |  -3361.400|  203857.000|  10133.962|  2696.844|    0|
| CALCIUM          |      0.121|     594.900|     45.795|    28.325|    0|
| CHLORIDE         |      0.036|   18012.742|    555.925|    53.542|    0|
| COLOR            |      0.000|     840.000|     39.935|    25.315|    1|
| COND             |      2.820|   64810.000|   3162.987|   688.356|    0|
| DOC              |      0.230|     515.810|     18.544|     8.287|    0|
| MAGNESIUM        |      0.067|    1023.000|     68.048|    24.561|    0|
| NITRATE\_N       |      0.000|      51.660|      1.555|     0.108|   52|
| NITRITE\_N       |      0.000|       0.419|      0.013|     0.001|  168|
| NTL              |      0.014|      54.000|      2.493|     1.123|    0|
| PH               |      2.830|      10.470|      0.845|     8.072|    0|
| POTASSIUM        |      0.041|    3376.000|    121.946|    11.799|    2|
| PTL              |      4.000|    3636.000|    269.738|   114.750|    0|
| SILICA           |      0.022|     935.000|     29.725|    10.882|    0|
| SODIUM           |      0.093|   29890.000|   1093.407|   109.473|    1|
| SULFATE          |      0.026|   47325.202|   1681.334|   194.297|    0|
| TURB             |      0.010|     447.150|     27.294|     9.451|   41|
| CHLX             |      0.000|     764.640|     54.082|    26.118|    5|
| CHLL             |      0.000|     584.640|     58.070|    27.332|    9|
| OXYGEN           |      0.250|      23.686|      2.447|     6.751|  170|
| TEMPERATURE      |      6.659|     335.001|     11.639|    21.765|  170|
| DEPTH            |      0.000|      25.000|      3.640|     3.264|  170|
| CONDUCTIVITY     |      1.780|   68863.636|   3828.352|   773.638|  170|
| SECCHI           |      0.020|      28.000|      2.311|     2.134|   75|
| AREA\_HA         |      1.033|  167489.609|   7501.797|   861.475|  100|
| ELEVATION        |    -53.270|    3594.970|    758.063|   646.201|  100|
| ABUNDANCE        |    267.000|   67860.000|   5494.833|  3685.472|    0|
| PERIM\_KM        |      0.394|    3520.774|    125.610|    21.095|  100|
| INDEX\_LAT\_DD   |     26.070|      48.985|      4.950|    40.760|    0|
| INDEX\_LON\_DD   |   -124.230|     -67.194|     14.842|   -95.078|    0|
| MMI\_BENT\_NLA12 |      0.000|      86.100|     15.820|    43.188|  222|
| MMI\_ZOOP\_NLA6  |      0.050|      94.650|     17.583|    55.213|   96|
| AMITOTAL         |      0.000|       2.045|      0.353|     0.360|  117|
| LitCvrQc3OE      |      0.000|       5.636|      0.717|     0.881|  117|
| LitRipCvrQc3OE   |      0.000|       4.696|      0.469|     0.735|  119|
| RDis\_IX         |      0.000|       0.950|      0.285|     0.488|  124|
| RVegQc3OE        |      0.000|       4.532|      0.508|     0.701|  119|
| MICX             |      0.000|      66.690|      3.535|     0.669|   92|
| ATRAZINE         |      0.000|       9.700|      0.486|     0.127|   94|
| METHYLMERCURY    |      0.080|      19.000|      1.568|     1.218|  222|
| TOTALHG          |      4.840|     859.730|     93.894|   103.161|  227|

AS it can be seen from the above result we have some missing values and
also two of the features–Elevation and ANC(Acid neutralizing capacity)
have some negative values. In the next section will try to impute the
missing values using the mice and mi packages.

### Summary of 2017 data

We can use the above defined function to do summary statistics on the
aggregated data for the year 2007. The summary will be done on the
numeric data.

``` r
# Summary for the numeric features
lakes07_summ <- summaries(select_if(lakes.07.df, is.numeric))

lakes07_summ %>% kable(format='markdown', digits = 3)%>% kable_styling(bootstrap_options = "striped", full_width = F, font_size = 12)
```

    ## Warning in kable_styling(., bootstrap_options = "striped", full_width =
    ## F, : Please specify format in kable. kableExtra can customize either HTML
    ## or LaTeX outputs. See https://haozhu233.github.io/kableExtra/ for details.

|               |           min|            max|            sd|           mean|  NAs|
|:--------------|-------------:|--------------:|-------------:|--------------:|----:|
| PH\_FIELD     |         4.100|   1.030000e+01|  8.990000e-01|   8.080000e+00|    9|
| PH\_LAB       |         4.160|   1.009000e+01|  7.650000e-01|   8.014000e+00|    0|
| COND          |         4.350|   5.059000e+04|  2.470393e+03|   6.652670e+02|    0|
| ANC           |       -62.960|   9.163290e+04|  5.830707e+03|   2.620119e+03|    0|
| TURB          |         0.147|   5.740000e+02|  3.413200e+01|   1.291600e+01|    0|
| TOC           |         0.370|   3.250500e+02|  2.002100e+01|   1.001200e+01|    0|
| DOC           |         0.340|   2.905700e+02|  1.690600e+01|   8.878000e+00|    0|
| NH4N\_PPM     |         0.004|   1.547000e+00|  1.100000e-01|   4.200000e-02|    0|
| NO3\_NO2      |         0.002|   5.592000e+00|  3.330000e-01|   6.900000e-02|    0|
| NTL\_PPM      |         0.010|   2.610000e+01|  2.154000e+00|   1.167000e+00|    0|
| PTL           |         0.714|   4.753400e+03|  2.698330e+02|   1.073340e+02|    0|
| CL\_PPM       |         0.050|   1.581431e+04|  5.251390e+02|   5.672500e+01|    0|
| NO3N\_PPM     |         0.002|   5.409000e+00|  3.080000e-01|   7.300000e-02|    0|
| SO4\_PPM      |         0.083|   4.008575e+04|  1.528241e+03|   1.887880e+02|    0|
| CA\_PPM       |         0.205|   4.857000e+02|  3.698100e+01|   2.782800e+01|    0|
| MG\_PPM       |         0.062|   2.466000e+03|  1.165320e+02|   2.706700e+01|    0|
| NA\_PPM       |         0.193|   1.674000e+04|  6.380970e+02|   8.697200e+01|    0|
| K\_PPM        |         0.050|   1.412000e+03|  5.395700e+01|   9.862000e+00|    0|
| COLOR         |         0.000|   1.650000e+02|  1.606700e+01|   1.618900e+01|    0|
| SIO2          |         0.025|   9.190700e+01|  1.061900e+01|   8.783000e+00|    0|
| NH4ION        |         0.000|   9.496400e+01|  6.522000e+00|   2.561000e+00|    0|
| CATSUM        |        28.670|   9.415390e+05|  3.757639e+04|   7.653919e+03|    0|
| ANSUM2        |        32.840|   9.632158e+05|  4.069073e+04|   8.155782e+03|    0|
| CHLA          |         0.068|   8.712000e+02|  6.470200e+01|   2.852400e+01|    5|
| SECMEAN       |         0.040|   3.671000e+01|  2.500000e+00|   2.186000e+00|   65|
| VISIT\_NO     |         1.000|   1.556000e+00|  1.380000e-01|   1.041000e+00|    0|
| LAT\_DD       |        26.936|   4.897900e+01|  5.036000e+00|   4.062000e+01|    0|
| LON\_DD       |      -124.633|  -6.769900e+01|  1.422700e+01|  -9.465800e+01|    0|
| HUC\_2        |         1.000|   1.800000e+01|  5.011000e+00|   8.455000e+00|    0|
| HUC\_8        |   1010002.000|   1.810020e+07|  5.016659e+06|   8.525925e+06|    0|
| DO2\_2M       |         0.800|   2.100000e+01|  1.863000e+00|   7.845000e+00|   55|
| ALBERS\_X     |  -2292120.601|   2.203317e+06|  1.162261e+06|   1.245475e+05|    0|
| ALBERS\_Y     |  -1055938.590|   1.524035e+06|  5.888666e+05|   4.369279e+05|    0|
| FLD\_LON\_DD  |      -124.621|  -6.769900e+01|  1.423400e+01|  -9.465500e+01|    1|
| FLD\_LAT\_DD  |        26.802|   4.898300e+01|  5.034000e+00|   4.061600e+01|    1|
| MDCATY        |         0.000|   7.600000e-01|  6.400000e-02|   5.500000e-02|    0|
| WGT           |         0.000|   7.703160e+02|  1.781560e+02|   8.549100e+01|    0|
| WGT\_NLA      |         0.000|   7.248870e+02|  9.154900e+01|   4.304700e+01|    0|
| ECO\_LEV\_3   |         1.000|   8.400000e+01|  2.032700e+01|   4.415300e+01|    0|
| AREA\_HA      |         4.037|   1.674896e+05|  8.020313e+03|   1.230252e+03|    0|
| LAKEAREA      |         0.040|   1.674896e+03|  8.020300e+01|   1.230300e+01|    0|
| LAKEPERIM     |         0.780|   2.763418e+03|  1.381510e+02|   3.299900e+01|    0|
| SLD           |         1.019|   2.863000e+01|  2.588000e+00|   2.644000e+00|    0|
| DEPTH\_X      |         0.500|   9.700000e+01|  1.021300e+01|   9.449000e+00|   17|
| DEPTHMAX      |         0.500|   9.700000e+01|  1.026900e+01|   9.494000e+00|    1|
| ELEV\_PT      |         0.000|   3.403000e+03|  6.788460e+02|   6.076520e+02|    0|
| COM\_ID       |         0.000|   2.453966e+07|  7.235670e+06|   1.184537e+07|    0|
| REACHCODE     |   2060003.000|   1.810020e+13|  5.047690e+12|   8.338619e+12|    1|
| ssiBedBld     |         0.000|   9.640000e-01|  1.310000e-01|   9.200000e-02|   57|
| ssiNATBedBld  |         0.000|   9.640000e-01|  1.080000e-01|   4.400000e-02|   57|
| rviLowWood    |         0.000|   1.702000e+00|  3.270000e-01|   4.210000e-01|   59|
| RVegQ\_7      |         0.000|   5.520000e-01|  1.070000e-01|   1.550000e-01|   59|
| RVegQ\_8      |         0.000|   5.750000e-01|  1.270000e-01|   2.160000e-01|   68|
| L\_RVegQ\_8   |        -2.000|  -2.330000e-01|  4.110000e-01|  -7.750000e-01|   68|
| LRCVQ\_7A     |         0.000|   9.500000e-01|  1.700000e-01|   3.120000e-01|   60|
| LRCVQ\_7B     |         0.000|   7.060000e-01|  1.150000e-01|   2.090000e-01|   62|
| LRCVQ\_7C     |         0.000|   5.840000e-01|  1.030000e-01|   1.830000e-01|   62|
| LRCVQ\_7D     |         0.000|   3.980000e-01|  7.800000e-02|   1.250000e-01|   62|
| LRCVQ\_8D     |         0.000|   4.450000e-01|  8.700000e-02|   1.560000e-01|   72|
| L\_LRCVQ\_8D  |        -2.000|  -3.420000e-01|  3.150000e-01|  -8.660000e-01|   72|
| ElevXLat      |         0.000|   1.412006e+05|  2.799303e+04|   2.570500e+04|   57|
| ElevDLat      |         0.000|   8.571300e+01|  1.707300e+01|   1.509200e+01|   57|
| ElevXLon      |   -375708.756|   0.000000e+00|  7.751939e+04|  -6.445280e+04|   57|
| XER           |         0.000|   1.000000e+00|  2.660000e-01|   7.600000e-02|   56|
| XER\_X\_Elev  |         0.000|   2.968800e+03|  3.982880e+02|   9.950400e+01|   56|
| WMT           |         0.000|   1.000000e+00|  3.530000e-01|   1.450000e-01|   56|
| RDisIXAgAdj5  |         0.000|   9.450000e-01|  2.760000e-01|   4.740000e-01|   57|
| RDisIXAgAdj4  |         0.000|   9.410000e-01|  2.740000e-01|   4.690000e-01|   57|
| RDisIXAgAdj3  |         0.000|   9.360000e-01|  2.720000e-01|   4.640000e-01|   57|
| RDisIXAgAdj2  |         0.000|   9.320000e-01|  2.700000e-01|   4.560000e-01|   57|
| RDis\_InEx    |         0.000|   9.320000e-01|  2.670000e-01|   4.440000e-01|   57|
| RDis\_IX      |         0.000|   9.450000e-01|  2.760000e-01|   4.740000e-01|   57|
| RVegQ         |         0.000|   5.580000e-01|  1.130000e-01|   1.710000e-01|   60|
| LogRVegQ      |        -2.000|  -2.460000e-01|  3.810000e-01|  -8.660000e-01|   60|
| LitCvrQ       |         0.000|   1.105000e+00|  1.120000e-01|   1.220000e-01|   60|
| LogLitCvrQ    |        -2.000|   4.700000e-02|  3.780000e-01|  -1.029000e+00|   60|
| LitRipCVQ     |         0.000|   5.880000e-01|  9.400000e-02|   1.470000e-01|   63|
| LogLitRipCvQ  |        -2.000|  -2.230000e-01|  3.200000e-01|  -9.020000e-01|   63|
| RVeg\_OE      |         0.000|   3.142000e+00|  4.760000e-01|   7.590000e-01|   60|
| LitCvr\_OE    |         0.000|   5.099000e+00|  6.760000e-01|   8.590000e-01|   60|
| LitRipCvr\_OE |         0.000|   3.041000e+00|  4.380000e-01|   7.620000e-01|   63|
| NTL           |         5.000|   2.610000e+04|  2.152594e+03|   1.166017e+03|    0|

``` r
summary(lakes.07.df$URBAN)
```

    ##    Length     Class      Mode 
    ##      1157 character character

As compared to the the 2012 data the 2007 data has fewer missing values.
In the next section, I will use `mice` and `im` packages to impute the
missing data.
